/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main1.Login_form_teacher.*;
import static main1.Login_form_teacher.t_code;
import static main1.teacher_file_upload.checkpoint_dic;
import static main1.teacher_file_upload.checkpoint_lang;
import static main1.update_question.checkpoint1;

/**
 *
 * @author Admin
 */
public class admin_home extends javax.swing.JFrame {
    //public static String t_code="room1";

    /**
     * Creates new form admin_home
     */
    public admin_home() {
        initComponents();
        file_upload.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_question = new javax.swing.JButton();
        update_question = new javax.swing.JButton();
        delete_question = new javax.swing.JButton();
        student_response = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enter_qn = new javax.swing.JTextField();
        set_qn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        student_record = new javax.swing.JTable();
        file_upload = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        question_record = new javax.swing.JTable();
        show_question = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1363, 716));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_question.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add_question.setLabel("ADD QUESTION");
        add_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_questionActionPerformed(evt);
            }
        });
        getContentPane().add(add_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 225, 102));

        update_question.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        update_question.setLabel("UPDATE QUESTION");
        update_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_questionActionPerformed(evt);
            }
        });
        getContentPane().add(update_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 229, 102));

        delete_question.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delete_question.setText("DELETE QUESTION");
        delete_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_questionActionPerformed(evt);
            }
        });
        getContentPane().add(delete_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 240, 100));

        student_response.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        student_response.setLabel("STUDENT RESPONSE");
        student_response.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_responseActionPerformed(evt);
            }
        });
        getContentPane().add(student_response, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 220, 100));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setLabel("NEW QUESTION SET");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN HOME PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 505, 43));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("ENTER THE NUMBER QUESTION IN VIVA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 390, 40));
        getContentPane().add(enter_qn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 200, 40));

        set_qn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        set_qn.setText("SET");
        set_qn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_qnActionPerformed(evt);
            }
        });
        getContentPane().add(set_qn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 170, 40));

        student_record.setBackground(new java.awt.Color(204, 204, 204));
        student_record.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        student_record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "NAME", "GENDER", "EMAIL", "SEAT NO", "CLASS"
            }
        ));
        student_record.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(student_record);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 1120, 150));

        file_upload.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        file_upload.setText("UPLOAD .DIC & .LM FILE");
        file_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_uploadActionPerformed(evt);
            }
        });
        getContentPane().add(file_upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 280, 110));

        logout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 190, 50));

        question_record.setBackground(new java.awt.Color(153, 153, 153));
        question_record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "QUESTION", "ANSWER"
            }
        ));
        jScrollPane2.setViewportView(question_record);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 1120, 140));

        show_question.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        show_question.setText("SHOW ALL QUESTION");
        show_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_questionActionPerformed(evt);
            }
        });
        getContentPane().add(show_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 463, 250, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_questionActionPerformed
        // TODO add your handling code here:
        //setVisible(false);
        new main1.add_question().setVisible(true);

    }//GEN-LAST:event_add_questionActionPerformed

    private void update_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_questionActionPerformed
        // TODO add your handling code here:
        //setVisible(false);
        new main1.update_question().setVisible(true);
    }//GEN-LAST:event_update_questionActionPerformed

    private void delete_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_questionActionPerformed
        // TODO add your handling code here:
        //setVisible(false);
        new main1.delete_question().setVisible(true);
    }//GEN-LAST:event_delete_questionActionPerformed

    private void set_qnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_qnActionPerformed
        // TODO add your handling code here:
        if(enter_qn.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"<html><h1><span style=\"color:red font:-size:10px\">PLEASE ENTER THE NO OF QUESTIONS TO BE ASKED<span></h1><html>","ALERT",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
            Statement st = conn.createStatement();
            PreparedStatement ps=conn.prepareStatement("update admin_records set NOQ=? where teacher_code=?");
            
            ps.setString(1,enter_qn.getText());
            ps.setString(2,t_code);
            ps.executeUpdate();
            //checkpoint1=0;
            JOptionPane.showMessageDialog(null,"<html><h1><span style=\"font:-size:10px\"><B>QUESTION NO IS UPDATED SUCCESSFULLY<br></B><span></h1><html>","ALERT",JOptionPane.INFORMATION_MESSAGE);
            //setVisible(false);
            //new admin_home().setVisible(true);
            }catch(Exception e){
                System.out.print(e);
            }
        }
    }//GEN-LAST:event_set_qnActionPerformed

    private void student_responseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_responseActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
            Statement st = conn.createStatement();
            ResultSet rs=st.executeQuery("select * from "+t_code);
            while(rs.next())
            {
                System.out.println("2");
                String arr[] = {rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
                DefaultTableModel tb = (DefaultTableModel)student_record.getModel();
                tb.addRow(arr);
            }
        }catch(Exception e)
        {
                System.out.print(e);
        }
    }//GEN-LAST:event_student_responseActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void file_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_uploadActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new teacher_file_upload().setVisible(true);
    }//GEN-LAST:event_file_uploadActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        
        if(file_upload.isEnabled())
        {
            if(checkpoint_dic && checkpoint_lang)
            {
                int j = JOptionPane.showConfirmDialog(null,"DO YOU REALLY WANT TO LOGOUT","SELECT",JOptionPane.YES_NO_OPTION);
                if(j==0)
                {
                  setVisible(false);
                  new Main_page().setVisible(true);   //logout
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"<html><h1><span style=\"color:red font:-size:10px\">PLEASE UPLOAD DICTIONARY(.dic) & LANGYAGE(.lm) FILE<span></h1><html>","ALERT",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        else
        {
            int j = JOptionPane.showConfirmDialog(null,"DO YOU REALLY WANT TO LOGOUT","SELECT",JOptionPane.YES_NO_OPTION);
            if(j==0)
            {
              setVisible(false);
              new Main_page().setVisible(true);   //logout
            }
            
        }
        
    }//GEN-LAST:event_logoutActionPerformed

    private void show_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_questionActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
            Statement st = conn.createStatement();
            ResultSet rs=st.executeQuery("select * from question_set where teacher_code='"+t_code+"'");
            while(rs.next())
            {
                System.out.println("2");
                String arr[] = {rs.getString(1),rs.getString(2),rs.getString(3)};
                DefaultTableModel tb = (DefaultTableModel)question_record.getModel();
                tb.addRow(arr);
            }
        }catch(Exception e)
        {
                System.out.print(e);
        }
    }//GEN-LAST:event_show_questionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_question;
    private javax.swing.JButton delete_question;
    private javax.swing.JTextField enter_qn;
    public static javax.swing.JButton file_upload;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logout;
    private javax.swing.JTable question_record;
    private javax.swing.JButton set_qn;
    private javax.swing.JButton show_question;
    private javax.swing.JTable student_record;
    private javax.swing.JButton student_response;
    private javax.swing.JButton update_question;
    // End of variables declaration//GEN-END:variables
}
