package grammer_file;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




import main1.*;
import grammer_file.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import java.util.Dictionary;
import static listener_file.File_upload3.answer_set;
import static listener_file.File_upload3.noq;
import static listener_file.File_upload3.question_set;
import static listener_file.File_upload3.key;
import static grammer_file.Practice_viva_room.score;
import static grammer_file.Practice_viva_room.*;
//import static main1.Viva_room1.score;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import static main1.Viva_room1.identify;
//import static main1.student_details.key;
//import Practice_viva_room.answer_set;


//import main.Home_page;
//import main.Login_form;

/**
 *
 * @author Admin
 */
public class Performance_evaluation22222 extends javax.swing.JFrame {
    public static String result_content = "";
    public static int score1 = 0;
    
    //public static Dictionary answer_set1 = new Hashtable();
    //public static Dictionary question_set1 = new Hashtable();
    //public static int noq=noq;
    

    /**
     * Creates new form Performance_evaluation
     */
    public static void getResult()
    {
        /*int c = 0;
        for (Enumeration k = answer_set.keys(); k.hasMoreElements();)
        {
            String temp_key1 = (String)k.nextElement();
            result_content = "\n"+result_content +"\n"+(c+1)+": "+ question_set.get(temp_key1)+"\nCORRECT ANSWER: "+answer_set1.get(temp_key1)+"\nYOUR ANSWER: "+Viva_room1.user_answer.get(temp_key1)+"\nTIME= "+Viva_room1.user_sec.get(temp_key1)+" sec"+"\n";
            c = c + 1;
        }*/
        int count1=0;
        while(count1<noq)
        {
            System.out.println(count1 +"l="+(noq));
            //display.setText("\n"+key[count]+": "+question_set.get(key[count]));
            //display.setText(display.getText()+"\n"+"Answer"+": "+answer_set.get(key[count]));
            result_content = "\n"+result_content +"\n"+(count1+1)+": "+ question_set.get(key[count1])+"\nCORRECT ANSWER: "+answer_set.get(key[count1])+"\nYOUR ANSWER: "+user_answer.get(key[count1])+"\nTIME= "+user_sec.get(key[count1])+" sec"+"\n";
            
            count1++;
        }
        
        /*try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project2","root","");
            PreparedStatement ps=conn.prepareStatement("insert into "+t_code+" (name,gender,email,seat_no,class,total_question,score)values(?,?,?,?,?,?,?)");
            
            ps.setString(1,name1);
            ps.setString(2,gender1);
            ps.setString(3,email1);
            ps.setString(4,seat_no1);
            ps.setString(5,s_class1);
            ps.setString(6,""+noq);
            ps.setString(7,""+score);
            ps.executeUpdate();
        } catch (Exception ex) {
            Logger.getLogger(Performance_evaluation22222.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
       
        
        analysis.setText(result_content);
        total1.setText(noq+"");
        correct_answer.setText(""+score);
        //correct_answer.setText(""+score);
        //wrong_answer.setText(""+(File_upload.noq-score));
        //average_time.setText(""+average+"\tsec");
        
    }
    public Performance_evaluation22222() {
        initComponents();
        getResult();
        back_to_home_page.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        analysis = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        total1 = new javax.swing.JTextField();
        correct_answer = new javax.swing.JTextField();
        wrong_answer = new javax.swing.JTextField();
        back_to_home_page = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        feedback = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        average_time = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1388, 905));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ANALYSIS OF YOUR PERFORMANCE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 64, -1, 39));

        analysis.setColumns(20);
        analysis.setRows(5);
        jScrollPane1.setViewportView(analysis);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 154, 957, 444));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("TOTAL NO OF QUESTION:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 183, -1, 33));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("CORRECT ANSWERED:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 229, 225, 34));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("WRONG ANSWERED:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 280, 225, 30));

        total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total1ActionPerformed(evt);
            }
        });
        getContentPane().add(total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 190, 110, 33));

        correct_answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correct_answerActionPerformed(evt);
            }
        });
        getContentPane().add(correct_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 230, 110, 30));
        getContentPane().add(wrong_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 280, 110, 32));

        back_to_home_page.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        back_to_home_page.setText("HOME PAGE");
        back_to_home_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_to_home_pageActionPerformed(evt);
            }
        });
        getContentPane().add(back_to_home_page, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 14, -1, 39));

        exit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1138, 11, 120, 42));

        save.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 89, 151, 47));

        feedback.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        feedback.setText("FEEDBACK");
        feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackActionPerformed(evt);
            }
        });
        getContentPane().add(feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 15, 210, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("AVEARGE TIME TAKEN:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, 225, 33));
        getContentPane().add(average_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1248, 310, 155, 33));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int j = JOptionPane.showConfirmDialog(null,"DO YOU WANT TO GIVE SOME FEEDBACK","SELECT",JOptionPane.YES_NO_OPTION);
        if(j==0)
        {
            
            new feedback().setVisible(true);
             //
        }
        else
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void back_to_home_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_to_home_pageActionPerformed
        // TODO add your handling code here:
        int j = JOptionPane.showConfirmDialog(null,"DO YOU REALLY WANT TO JUMP TO HOMEPAGE","SELECT",JOptionPane.YES_NO_OPTION);
        if(j==0)
        {
            analysis.setText("");
            result_content="";
            score=0;
          setVisible(false);
          new Main_page().setVisible(true);  //
        }
    }//GEN-LAST:event_back_to_home_pageActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
          Performance_evaluation1.forwhome = "Personal_user";
          new Save_file().setVisible(true);
    }//GEN-LAST:event_saveActionPerformed

    private void feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackActionPerformed
        // TODO add your handling code here:
        //new feedback().setVisible(true);
    }//GEN-LAST:event_feedbackActionPerformed

    private void total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total1ActionPerformed

    private void correct_answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correct_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correct_answerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Performance_evaluation22222.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Performance_evaluation22222.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Performance_evaluation22222.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Performance_evaluation22222.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Performance_evaluation22222().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea analysis;
    private static javax.swing.JLabel average_time;
    private javax.swing.JButton back_to_home_page;
    private static javax.swing.JTextField correct_answer;
    private javax.swing.JButton exit;
    private javax.swing.JButton feedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save;
    private static javax.swing.JTextField total1;
    private static javax.swing.JTextField wrong_answer;
    // End of variables declaration//GEN-END:variables
}
